# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mw_v11.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 761)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMouseTracking(True)
        self.win_con = QLabel(self.centralwidget)
        self.win_con.setObjectName(u"win_con")
        self.win_con.setGeometry(QRect(0, 0, 1281, 41))
        self.win_con.setMouseTracking(True)
        self.settings_group = QGroupBox(self.centralwidget)
        self.settings_group.setObjectName(u"settings_group")
        self.settings_group.setGeometry(QRect(240, 130, 801, 471))
        self.settings_group.setMouseTracking(True)
        self.settings = QLabel(self.settings_group)
        self.settings.setObjectName(u"settings")
        self.settings.setGeometry(QRect(0, 0, 241, 471))
        self.settings.setMouseTracking(True)
        self.setting_sel = QLabel(self.settings_group)
        self.setting_sel.setObjectName(u"setting_sel")
        self.setting_sel.setGeometry(QRect(240, 0, 561, 471))
        self.setting_sel.setMouseTracking(True)
        self.setting_exit = QLabel(self.settings_group)
        self.setting_exit.setObjectName(u"setting_exit")
        self.setting_exit.setGeometry(QRect(723, 30, 41, 41))
        self.setting_exit.setMouseTracking(True)
        self.settingsel_path = QLabel(self.settings_group)
        self.settingsel_path.setObjectName(u"settingsel_path")
        self.settingsel_path.setGeometry(QRect(0, 80, 241, 51))
        self.settingsel_path_bgp = QLabel(self.settings_group)
        self.settingsel_path_bgp.setObjectName(u"settingsel_path_bgp")
        self.settingsel_path_bgp.setGeometry(QRect(270, 60, 221, 51))
        self.settingsel_path_bgp_show = QLabel(self.settings_group)
        self.settingsel_path_bgp_show.setObjectName(u"settingsel_path_bgp_show")
        self.settingsel_path_bgp_show.setGeometry(QRect(270, 120, 381, 41))
        self.settingsel_path_bgp_selbt = QLabel(self.settings_group)
        self.settingsel_path_bgp_selbt.setObjectName(u"settingsel_path_bgp_selbt")
        self.settingsel_path_bgp_selbt.setGeometry(QRect(670, 120, 121, 41))
        font = QFont()
        font.setPointSize(15)
        self.settingsel_path_bgp_selbt.setFont(font)
        self.settingsel_path_bgp_selbt.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.settingsel_path_gl = QLabel(self.settings_group)
        self.settingsel_path_gl.setObjectName(u"settingsel_path_gl")
        self.settingsel_path_gl.setGeometry(QRect(270, 190, 221, 51))
        self.settingsel_path_gl_show = QLabel(self.settings_group)
        self.settingsel_path_gl_show.setObjectName(u"settingsel_path_gl_show")
        self.settingsel_path_gl_show.setGeometry(QRect(270, 250, 381, 41))
        self.settingsel_path_gl_selbt = QLabel(self.settings_group)
        self.settingsel_path_gl_selbt.setObjectName(u"settingsel_path_gl_selbt")
        self.settingsel_path_gl_selbt.setGeometry(QRect(670, 250, 121, 41))
        self.settingsel_path_gl_selbt.setFont(font)
        self.settingsel_path_gl_selbt.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.settingsel_path_gs = QLabel(self.settings_group)
        self.settingsel_path_gs.setObjectName(u"settingsel_path_gs")
        self.settingsel_path_gs.setGeometry(QRect(270, 320, 221, 51))
        self.settingsel_path_gs_show = QLabel(self.settings_group)
        self.settingsel_path_gs_show.setObjectName(u"settingsel_path_gs_show")
        self.settingsel_path_gs_show.setGeometry(QRect(270, 380, 381, 41))
        self.settingsel_path_gs_selbt = QLabel(self.settings_group)
        self.settingsel_path_gs_selbt.setObjectName(u"settingsel_path_gs_selbt")
        self.settingsel_path_gs_selbt.setGeometry(QRect(670, 380, 121, 41))
        self.settingsel_path_gs_selbt.setFont(font)
        self.settingsel_path_gs_selbt.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.settingsel_change2i = QLabel(self.settings_group)
        self.settingsel_change2i.setObjectName(u"settingsel_change2i")
        self.settingsel_change2i.setGeometry(QRect(0, 140, 241, 51))
        self.settingsel_change2i_zip = QLabel(self.settings_group)
        self.settingsel_change2i_zip.setObjectName(u"settingsel_change2i_zip")
        self.settingsel_change2i_zip.setGeometry(QRect(270, 61, 221, 51))
        self.settingsel_change2i_zip_show = QLabel(self.settings_group)
        self.settingsel_change2i_zip_show.setObjectName(u"settingsel_change2i_zip_show")
        self.settingsel_change2i_zip_show.setGeometry(QRect(270, 120, 221, 51))
        font1 = QFont()
        font1.setPointSize(20)
        self.settingsel_change2i_zip_show.setFont(font1)
        self.settingsel_change2i_zip_show.setAlignment(Qt.AlignCenter)
        self.settingsel_change2i_zip_selbt = QLabel(self.settings_group)
        self.settingsel_change2i_zip_selbt.setObjectName(u"settingsel_change2i_zip_selbt")
        self.settingsel_change2i_zip_selbt.setGeometry(QRect(530, 130, 121, 41))
        self.settingsel_change2i_zip_selbt.setFont(font)
        self.settingsel_change2i_zip_selbt.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.settingsel_change2i_selbt = QLabel(self.settings_group)
        self.settingsel_change2i_selbt.setObjectName(u"settingsel_change2i_selbt")
        self.settingsel_change2i_selbt.setGeometry(QRect(370, 220, 121, 41))
        self.settingsel_change2i_selbt.setFont(font)
        self.settingsel_change2i_selbt.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.settingsel_change2i_download = QLabel(self.settings_group)
        self.settingsel_change2i_download.setObjectName(u"settingsel_change2i_download")
        self.settingsel_change2i_download.setGeometry(QRect(600, 420, 181, 31))
        self.settingsel_change2i_download.setFont(font)
        self.settingsel_change2i_download.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.settingsel_change2i_article = QLabel(self.settings_group)
        self.settingsel_change2i_article.setObjectName(u"settingsel_change2i_article")
        self.settingsel_change2i_article.setGeometry(QRect(600, 390, 181, 31))
        self.settingsel_change2i_article.setFont(font)
        self.settingsel_change2i_article.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.settingsel_change2i_delete = QLabel(self.settings_group)
        self.settingsel_change2i_delete.setObjectName(u"settingsel_change2i_delete")
        self.settingsel_change2i_delete.setGeometry(QRect(600, 350, 181, 31))
        self.settingsel_change2i_delete.setFont(font)
        self.settingsel_change2i_delete.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.gl_setup_text = QLabel(self.centralwidget)
        self.gl_setup_text.setObjectName(u"gl_setup_text")
        self.gl_setup_text.setGeometry(QRect(120, 100, 1031, 71))
        self.gl_setup_text.setFont(font1)
        self.gl_setup_text.setMouseTracking(True)
        self.gl_setup_text.setAlignment(Qt.AlignCenter)
        self.gl_setup_path_show = QLineEdit(self.centralwidget)
        self.gl_setup_path_show.setObjectName(u"gl_setup_path_show")
        self.gl_setup_path_show.setGeometry(QRect(100, 250, 791, 61))
        font2 = QFont()
        font2.setPointSize(17)
        self.gl_setup_path_show.setFont(font2)
        self.gl_setup_path_sel = QPushButton(self.centralwidget)
        self.gl_setup_path_sel.setObjectName(u"gl_setup_path_sel")
        self.gl_setup_path_sel.setGeometry(QRect(974, 252, 171, 61))
        self.gl_setup_path_sel.setFont(font2)
        self.gl_setup_path_sel.setMouseTracking(True)
        self.bgp_show = QLabel(self.centralwidget)
        self.bgp_show.setObjectName(u"bgp_show")
        self.bgp_show.setGeometry(QRect(0, 40, 1281, 720))
        self.bgp_show.setMouseTracking(True)
        self.gl_setup_confirm = QPushButton(self.centralwidget)
        self.gl_setup_confirm.setObjectName(u"gl_setup_confirm")
        self.gl_setup_confirm.setGeometry(QRect(540, 410, 191, 71))
        self.gl_setup_confirm.setFont(font2)
        self.gl_setup_confirm.setMouseTracking(True)
        self.modesel = QComboBox(self.centralwidget)
        self.modesel.addItem("")
        self.modesel.addItem("")
        self.modesel.addItem("")
        self.modesel.addItem("")
        self.modesel.addItem("")
        self.modesel.setObjectName(u"modesel")
        self.modesel.setGeometry(QRect(850, 540, 391, 51))
        self.modesel.setFont(font2)
        self.modesel.setMaxVisibleItems(4)
        self.modesel.setInsertPolicy(QComboBox.InsertAtBottom)
        self.mode_set = QLabel(self.centralwidget)
        self.mode_set.setObjectName(u"mode_set")
        self.mode_set.setGeometry(QRect(1063, 620, 181, 61))
        self.mode_set.setFont(font2)
        self.mode_set.setAlignment(Qt.AlignCenter)
        self.mode_set_done = QLabel(self.centralwidget)
        self.mode_set_done.setObjectName(u"mode_set_done")
        self.mode_set_done.setGeometry(QRect(530, 630, 231, 41))
        self.start_game = QLabel(self.centralwidget)
        self.start_game.setObjectName(u"start_game")
        self.start_game.setGeometry(QRect(823, 620, 211, 61))
        self.start_launcher = QLabel(self.centralwidget)
        self.start_launcher.setObjectName(u"start_launcher")
        self.start_launcher.setGeometry(QRect(533, 620, 261, 61))
        self.start_bwiki = QLabel(self.centralwidget)
        self.start_bwiki.setObjectName(u"start_bwiki")
        self.start_bwiki.setGeometry(QRect(1030, 700, 131, 41))
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(20, 60, 1241, 631))
        self.bwiki_webview = QVBoxLayout(self.verticalLayoutWidget)
        self.bwiki_webview.setObjectName(u"bwiki_webview")
        self.bwiki_webview.setContentsMargins(0, 0, 0, 0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.bgp_show.raise_()
        self.win_con.raise_()
        self.gl_setup_text.raise_()
        self.gl_setup_path_show.raise_()
        self.gl_setup_path_sel.raise_()
        self.gl_setup_confirm.raise_()
        self.modesel.raise_()
        self.mode_set.raise_()
        self.start_game.raise_()
        self.start_launcher.raise_()
        self.settings_group.raise_()
        self.mode_set_done.raise_()
        self.start_bwiki.raise_()
        self.verticalLayoutWidget.raise_()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u542f\u52a8\u5668", None))
        self.win_con.setText("")
        self.settings_group.setTitle("")
        self.settings.setText("")
        self.setting_sel.setText("")
        self.setting_exit.setText("")
        self.settingsel_path.setText("")
        self.settingsel_path_bgp.setText("")
        self.settingsel_path_bgp_show.setText("")
        self.settingsel_path_bgp_selbt.setText("")
        self.settingsel_path_gl.setText("")
        self.settingsel_path_gl_show.setText("")
        self.settingsel_path_gl_selbt.setText("")
        self.settingsel_path_gs.setText("")
        self.settingsel_path_gs_show.setText("")
        self.settingsel_path_gs_selbt.setText("")
        self.settingsel_change2i.setText("")
        self.settingsel_change2i_zip.setText("")
        self.settingsel_change2i_zip_show.setText(QCoreApplication.translate("MainWindow", u"\u672a\u9009\u62e9", None))
        self.settingsel_change2i_zip_selbt.setText("")
        self.settingsel_change2i_selbt.setText("")
        self.settingsel_change2i_download.setText("")
        self.settingsel_change2i_article.setText("")
        self.settingsel_change2i_delete.setText("")
        self.gl_setup_text.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e\u6e38\u620f\u542f\u52a8\u5668\u5b89\u88c5\u8def\u5f84", None))
        self.gl_setup_path_sel.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9", None))
        self.bgp_show.setText("")
        self.gl_setup_confirm.setText(QCoreApplication.translate("MainWindow", u"\u786e\u8ba4", None))
        self.modesel.setItemText(0, QCoreApplication.translate("MainWindow", u"\u9ed8\u8ba4", None))
        self.modesel.setItemText(1, QCoreApplication.translate("MainWindow", u"\u56fd\u670d\uff08\u5b98\u670d\uff09", None))
        self.modesel.setItemText(2, QCoreApplication.translate("MainWindow", u"\u56fd\u670d\uff08\u5b98\u670d\uff09+ taptap", None))
        self.modesel.setItemText(3, QCoreApplication.translate("MainWindow", u"Bilibili\u670d\uff08\u6e20\u9053\u670d\uff09", None))
        self.modesel.setItemText(4, QCoreApplication.translate("MainWindow", u"\u56fd\u9645\u670d", None))

        self.mode_set.setText("")
        self.mode_set_done.setText("")
        self.start_game.setText("")
        self.start_launcher.setText("")
        self.start_bwiki.setText("")
    # retranslateUi

